import Header from "@/Layout/header";
import Head from "next/head";
import React from "react";

function Owner() {
  return (
    <>
      <Head>
        <title>オーナー制ぶどう</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Owner</h1>
    </>
  );
}

export default Owner;
