import Header from "@/Layout/header";
import Head from "next/head";
import React from "react";

function Shop() {
  return (
    <>
      <Head>
        <title>オンラインショップ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Shop</h1>
    </>
  );
}

export default Shop;
